# Generated by Django 4.2.6 on 2023-10-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leccion',
            name='curso',
        ),
        migrations.AddField(
            model_name='leccion',
            name='capitulo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lessons.capitulo'),
            preserve_default=False,
        ),
    ]
