# Generated by Django 4.2.6 on 2023-10-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_leccion_curso_leccion_capitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoqueAprenderas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.curso')),
            ],
        ),
    ]
