# Generated by Django 4.2.6 on 2023-10-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_loqueaprenderas_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loqueaprenderas',
            name='description',
        ),
    ]
