# Generated by Django 4.2.6 on 2023-10-19 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0007_remove_compra_usuario_compra_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='compra',
            name='customer_id_stripe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
