# Generated by Django 4.2.6 on 2023-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_remove_compra_customer_id_stripe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='video_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
